#!/bin/zsh
##? _systemctl_unit_state - fix problem with completions for systemctl

#function _systemctl_unit_state {
typeset -gA _sys_unit_state
_sys_unit_state=( $(__systemctl list-unit-files "$PREFIX*" | awk '{print $1, $2}') )
#}